### ISSUE TITLE
Plotting Crashes on `create2_docker.py` and `create2_mover.py` Scripts

### ISSUE THREAD

**Issue by dylanashley** [kindredresearch/SenseAct#15]
Plotting on both the `create2_docker.py` and `create2_mover.py` scripts crashes after running for a few minutes with the following error:

```
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "create2_mover.py", line 186, in plot_create2_mover
    ax2.set_ylim([np.min(rets), np.max(rets) + 1])
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2442, in amin
    initial=initial)
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 83, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```

For reference this is running on a Raspberry Pi 3 and the plotting is being sent via X-forwarding through SSH to a MacBook.

**Comment by armahmood** [comment]
No repeat of this issue.
