### ISSUE TITLE
UR Reacher on CB2

### ISSUE THREAD

**Issue by nlynn12** [kindredresearch/SenseAct#37]
**System:** I'm using PR #29 on Ubuntu 18.04 with both real UR5s and the URSim in Virtualbox

**Intro:** I've successfully run SenseAct on the CB3 ([v.3.7.0](https://www.universal-robots.com/download/?option=44060#section16597)) and the new e-series ([v.5.1.2](https://www.universal-robots.com/download/?option=45451#section41570)) simulators. I've furthermore tested the code "as is", and on a real CB2 which didn't work.

**Problem:** I think it's because of the `_compute_sensation` function in [reacher_env.py](../blob/master/senseact/envs/ur/reacher_env.py#L362), uses the following commands `'i_control'`, `'v_actual'`, `'safety_mode'`, which is unavailable on the CB2.

Is the three above-mentioned commands actually used? It doesn't seem like it, so I'll try to download the CB2 ([v.1.8.14035](https://www.universal-robots.com/download/?option=16624#section16597)) simulator and try it out with the three commands removed.

**Comment by nlynn12** [comment]
Running the code "as is" on CB2 (v.1.8.14035)

```bash
$ python ur5_reacher.py 
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
2018-10-16 22:08:56.493242: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/rtrl_base_env.py", line 479, in _run_loop_
    self._sensor_to_sensation_()
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/rtrl_base_env.py", line 334, in _sensor_to_sensation_
    s = self._compute_sensation_(name, sensor_window, timestamp_window, index_window)
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/envs/ur/reacher_env.py", line 397, in _compute_sensation_
    self._currentc_ = np.array([sensor_window[i]['i_control'][0] for i in range(index_start,index_end)])
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/envs/ur/reacher_env.py", line 397, in <listcomp>
    self._currentc_ = np.array([sensor_window[i]['i_control'][0] for i in range(index_start,index_end)])
ValueError: no field of name i_control
Started plotting routine
Warning: incomplete packet from UR
 buffer size must be a multiple of element size Could not convert data.
Init param sum -2.3423016
********** Iteration 0 ************
sampling
```

**Comment by nlynn12** [comment]
With line [#L397](../blob/master/senseact/envs/ur/reacher_env.py#L397) [#L399](../blob/master/senseact/envs/ur/reacher_env.py#L399) and [#L400](../blob/master/senseact/envs/ur/reacher_env.py#L400) outcommented I get the following

```bash
$ python ur5_reacher.py 
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
2018-10-16 22:08:20.909136: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Started plotting routine
Warning: incomplete packet from UR
 buffer size must be a multiple of element size Could not convert data.
Init param sum -2.3423016
********** Iteration 0 ************
sampling
Resetting
Warning: incomplete packet from UR
 buffer size must be a multiple of element size Could not convert data.
Warning: incomplete packet from UR
 buffer size must be a multiple of element size Could not convert data.
Warning: incomplete packet from UR
 buffer size must be a multiple of element size Could not convert data.
Warning: incomplete packet from UR
 buffer size must be a multiple of element size Could not convert data.
Reset done
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/rtrl_base_env.py", line 480, in _run_loop_
    self._action_to_actuator_()
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/rtrl_base_env.py", line 351, in _action_to_actuator_
    self._compute_actuation_(action[0], timestamp, index)
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/envs/ur/reacher_env.py", line 461, in _compute_actuation_
    self.close()
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/rtrl_base_env.py", line 263, in close
    comm.join()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
ERROR:root:One of the environment subprocess has died, closing all processes.
Traceback (most recent call last):
  File "ur5_reacher.py", line 185, in <module>
    main()
  File "ur5_reacher.py", line 84, in main
    callback=kindred_callback
  File "/home/nily/Projects/SenseAct/lib/python3.6/site-packages/baselines/trpo_mpi/trpo_mpi.py", line 199, in learn
    seg = seg_gen.__next__()
  File "/home/nily/Projects/SenseAct/lib/python3.6/site-packages/baselines/trpo_mpi/trpo_mpi.py", line 56, in traj_segment_generator
    ob, rew, new, _ = env.step(ac)
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/utils.py", line 150, in step
    wrapped_step = self._wrapped_env.step(scaled_action)
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/rtrl_base_env.py", line 243, in step
    self.act(action)
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/rtrl_base_env.py", line 235, in act
    raise e
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/rtrl_base_env.py", line 232, in act
    self._write_action(action)
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/rtrl_base_env.py", line 401, in _write_action
    raise Exception("Environment has been shutdown due to subprocess error.")
Exception: Environment has been shutdown due to subprocess error.
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 749, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "ur5_reacher.py", line 125, in plot_ur5_reacher
    old_size = len(shared_returns['episodic_returns'])
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 753, in _callmethod
    self._connect()
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 740, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by dkorenkevych** [comment]
Our UR code was built around UR Software version 3.3.4.310. Apparently CB2 version has different output packet format. Please take a look at https://github.com/kindredresearch/SenseAct/blob/master/senseact/devices/ur/ur_utils.py. You should be able to modify the REALTIME_COMM_PACKET_SIZE and the REALTIME_COMM_PACKET constants to meet the CB2 requirements.

**Comment by nlynn12** [comment]
In PR #29 the REALTIME_COMM_PACKET_SIZE = 812 and REALTIME_COMM_PACKET is set accordingly to the firmware version. But it is not working. Please see the output above.

**Comment by dkorenkevych** [comment]
The warning message in the output is issued by this code https://github.com/kindredresearch/SenseAct/blob/6341ca492186d578f8c7ec55c90453917061b576/senseact/devices/ur/ur_communicator.py#L272-L274, which means the packet size received from the arm is not 812 bytes. In the UR [client interface](https://s3-eu-west-1.amazonaws.com/ur-support-site/16496/Client_Interface_V3.7andV5.1.xlsx) for v1.8 it is mentioned: "If it is experienced that less than 756 bytes are received, the protocol for the actual received bytes also follows the structure listed above, only not containing the entries at leading up the 756th byte." We currently do not have a robot with CB2 software version to test this, but could you confirm the packet size you are receiving is less than 756 bytes? It is the size of data variable at https://github.com/kindredresearch/SenseAct/blob/6341ca492186d578f8c7ec55c90453917061b576/senseact/devices/ur/ur_communicator.py#L113

Alternatively, consider upgrading your robot software to CB 3.1 to make it compatible with current version of SenseAct.

**Comment by nlynn12** [comment]
I can try to confirm this tomorrow. Btw. you don’t need the actual UR robot to test it. Simply download the URSim simulator from:  https://www.universal-robots.com/download/

Simply choose robot type (your choice) ->Software -> Offline Simulator -> Non linux -> Version (your choice).

And no matter what system you have, choose non-linux. They use a very old Java version (v1.6) and it's near to impossible to make the simulator work natively in Ubuntu. It runs so much better in virtualbox! Remember to set the network settings to bridge.

Now you can test your code on any of the UR software versions.

**Comment by dkorenkevych** [comment]
I made a fix https://github.com/kindredresearch/SenseAct/pull/41 that should help with the 756 bytes and other similar issues.

**Comment by nlynn12** [comment]
Cool, so I'm not getting the error with the 756 bytes anymore. However I put the line before the `self.pre_check(data)`

But now I get an error from the reacher_env.py

```
Process Process-2:
WARNING:root:Agent has over-run its allocated dt, it has been 0.05085325241088867 since the last observation, 0.010853252410888671 more than allowed
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/rtrl_base_env.py", line 480, in _run_loop_
    self._action_to_actuator_()
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/rtrl_base_env.py", line 351, in _action_to_actuator_
    self._compute_actuation_(action[0], timestamp, index)
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/envs/ur/reacher_env.py", line 462, in _compute_actuation_
    self.close()
  File "/home/nily/Projects/SenseAct/SenseAct/senseact/rtrl_base_env.py", line 263, in close
    comm.join()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
4.541507005691528: Hiccup of 8.00ms overhead between UR packets)
ERROR:root:One of the environment subprocess has died, closing all processes.
```

**Comment by dkorenkevych** [comment]
Updated PR https://github.com/kindredresearch/SenseAct/pull/41, should fix the above issue.

**Comment by nlynn12** [comment]
I still get the same error.

```bash
Fatal UR5 error: safety_mode=None
Process Process-2:
WARNING:root:Agent has over-run its allocated dt, it has been 0.07109928131103516 since the last observation, 0.031099281311035155 more than allowed

```

**Comment by dkorenkevych** [comment]
Sure, my oversight. Updated https://github.com/kindredresearch/SenseAct/pull/41 again. Could you please see if it works now?

**Comment by nlynn12** [comment]
Perfect. It works now with the aforementioned lines outcommented. :+1: Thank you Dmytro!

**Comment by dkorenkevych** [comment]
Great to know it works, thank you for patience!
